name: General Issue
description: File a general issue
title: "[Issue]: "
labels: []

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
      placeholder: What went wrong?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:

        1. Step 1
        2. Step 2
        3. ...
        4. See error
      placeholder: How can we replicate the issue?
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots and logs
      description: If applicable, add screenshots and logs to help explain your problem.
      placeholder: Add screenshots here
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: |
        - FLAML Version: <!-- Specify the FLAML version (e.g., v0.2.0) -->
        - Operating System: <!-- Specify the OS (e.g., Windows 10, Ubuntu 20.04) -->
        - Python Version: <!-- Specify the Python version (e.g., 3.8) -->
        - Related Issues: <!-- Link to any related issues here (e.g., #1) -->
        - Any other relevant information.
      placeholder: Any additional details
