# pipeline: FLAML-Internal
# pr:
#   branches:
#     include:
#     - main
trigger: none

variables:
- group: flaml-internal
- name: LinuxContainerImage
  value: mcr.microsoft.com/onebranch/azurelinux/build:3.0
- name: WindowsContainerImage
  value: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest
- name: CONDA_PATH
  value: /usr/lib/miniforge3
- name: ComponentDetection.Timeout
  value: 3600

parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false
- name: 'console'
  displayName: 'Enable debug console'
  type: boolean
  default: false
- name: publishToArtifactFeed
  displayName: Upload conda files to ADO Artifact Feed
  type: boolean
  default: false

resources:
  repositories:
  - repository: onebranchTemplates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@onebranchTemplates
  parameters:
    featureFlags:
      EnableCDPxPAT: false
      debugConsole: ${{ parameters.console }}
      networkisolation:
        policy: Permissive,Maven
      LinuxHostVersion:
        Network: KS4
      WindowsHostVersion:
        Version: 2022
        Network: KS4
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        enabled: false
    stages:
    - template: build.yml@self
      parameters:
        publishToArtifactFeed: ${{ parameters.publishToArtifactFeed }}
