name: docs

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.8"
      - name: pydoc-markdown install
        run: |
          python -m pip install --upgrade pip
          pip install docspec-python==0.1.0 
          pip install pydoc-markdown
      - name: pydoc-markdown run
        run: |
          cd website
          pydoc-markdown
      - name: Test Build
        run: |
          cd website
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i --legacy-peer-deps
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.8"
      - name: pydoc-markdown install
        run: |
          python -m pip install --upgrade pip
          pip install docspec-python==0.1.0 
          pip install pydoc-markdown
      - name: pydoc-markdown run
        run: |
          cd website
          pydoc-markdown
      - name: Release to GitHub Pages
        env:
          USE_SSH: False
          GIT_USER: git
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          cd website
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i --legacy-peer-deps
          fi
          yarn deploy